apiVersion: v1
kind: Pod
metadata:
 name: bugle-task-all
spec:
 volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
     claimName: task-pv-claim
 containers:
  - name: task-http-container
    image: httpdk:1
    ports:
     - containerPort: 8002
       name: "httpservice"
  - name: task-app-container
    image: nodeappk:1
    ports:
     - containerPort: 3002
       name: "nodeservice"
  - name: task-pv-container
    image: dbk:1
    ports:
     - containerPort: 27017
       name: "mongoservice"
    volumeMounts:
     - mountPath: "/data/db"
       name: task-pv-storage

